{% set name = "pelican" %}
{% set version = "4.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pelican-{{ version }}.tar.gz
  sha256: 04932e82dc7542bae7f1830710978836ca00608aa4ece7206dc13185a08c4562

build:
  number: 0
  noarch: python
  entry_points:
    - pelican = pelican.__main__:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-plugins = pelican.plugins._utils:list_plugins
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4.0
    - pdm-backend
    - pip
  run:
    - python >=3.9,<4.0
    - blinker >=1.7.0
    - docutils >=0.20.1
    - feedgenerator >=2.1.0
    - jinja2 >=3.1.2
    - ordered-set >=4.1.0
    - pygments >=2.16.1
    - python-dateutil >=2.8.2
    - rich >=13.6.0
    - unidecode >=1.3.7
    - watchfiles >=0.21.0

test:
  imports:
    - pelican
    - pelican.plugins
  commands:
    - pip check
    - pelican --help
    - pelican-import --help
    - pelican-plugins --help
    - pelican-quickstart --help
    - pelican-themes --help
  requires:
    - pip

about:
  home: http://getpelican.com/
  license_file: LICENSE
  license: AGPL-3.0-only
  summary: A tool to generate a static blog from reStructuredText or Markdown input files.

extra:
  recipe-maintainers:
    - ocefpaf
    - mwcraig
